### PR TITLE
Spell `Voilà` properly in README.md

### PR DESCRIPTION
**Pull request by LeSeulArtichaut**
*There's two kind of people in this world. Those who spell French properly, and those who don't.*

### CODE REVIEW

**Comment by LeSeulArtichaut** [comment]
NB: this is more of a joke than an actual need. I think nobody cares about a single `

**Comment by mark-i-m** [comment]
There are two kinds of people in the world: those that have French keyboards, and those that don't :P

**Comment by LeSeulArtichaut** [comment]
I nailed that answer ^^

**Comment by Purpzie** [comment]
Apologies if I shouldn't be commenting on this (I'm relatively new to rust, just exploring around atm), but - this PR made me wheeze in the middle of class.
This entire community seems extremely wholesome, oh my goodness.

**Pull request merged**
