### PR TITLE
no problem was mentioned before then

### PR DESCRIPTION
**Pull request by tshepang**

### CODE REVIEW

**Comment by spastorino** [comment]
What about using `which commits are causing problems`.

**Comment by tshepang** [comment]
A "git bisect" would imply there is a problem, not problem*s*. Beyond that, it's not a pretty sentence, and I don't feel that `git bisect` needs to be mentioned at that point... feels too specific.

**Comment by tshepang** [comment]
Re-reading the sentence, am not even sure my commit improves things, so feel free to close

**Comment by spastorino** [comment]
What I thought you wanted to improve was the fact that saying a problem means that there's just one problem but could be more than one. If you keep coding without testing and at the end you see failures and run git blame there could be multiple problems.

If it makes sense to you go with something like that, otherwise, yeah we can close it I think.

**Pull request closed without merging**
