### PR TITLE
fix chalk links

### PR DESCRIPTION
**Pull request by tshepang**

### CODE REVIEW

**Comment by JohnTitor** [comment]
According to the CI, we should update more links.

**Comment by JohnTitor** [comment]
You should update the links in this file (https://github.com/rust-lang/rustc-guide/blob/master/src/macro-expansion.md) from `ext/tt` to `ext/mbe`.

**Comment by tshepang** [comment]
Ok, was only focused on chalk links... will fix those also.

**Comment by JohnTitor** [comment]
Thanks! Looks good to me.

**Pull request merged**
