### PR TITLE
Add some documentation about updating LLVM

### PR DESCRIPTION
**Pull request by alexcrichton**
I was talking with @tromey about LLDB/clang updates and I think it's about time we document all this!

### CODE REVIEW

**Comment by mark-i-m** [comment]
@alexcrichton Do you have any plans to write more about LLVM or codegen? It would be very welcome.

**Comment by tromey** [comment]
Thanks for doing this.  It looks good to me.

**Comment by alexcrichton** [comment]
@mark-i-m I don't have plans just yet, but perhaps in the future!

**Comment by alexcrichton** [comment]
Updated!

**Pull request merged**
