### PR TITLE
Libsyntax was split apart

### PR DESCRIPTION
**Pull request by mark-i-m**
cc https://github.com/rust-lang/rust/pull/65324

r? @Centril or @petrochenkov 

This fixes some links.

### CODE REVIEW

**Comment by Centril** [comment]
Looks good :)

**Comment by mark-i-m** [comment]
@Centril could you use the github approve feature. That would unblock github from merging the PR. Thanks :)

**Comment by Centril** [comment]
@mark-i-m guess not? ;)

**Comment by JohnTitor** [comment]
approved behalf of @Centril

**Pull request merged**
