### PR TITLE
Update sanitizers documentation

### PR DESCRIPTION
**Pull request by tmiasko**

### CODE REVIEW

**Comment by nikomatsakis** [comment]
Thanks again for doing this. =)

**Comment by mark-i-m** [comment]
Ping @tmiasko any updates?

**Comment by tmiasko** [comment]
In part this describes changes from rust-lang/rust#68164 which are yet to land. If that is not an issue we could merge it now and update later as necessary.

**Comment by spastorino** [comment]
Thanks @tmiasko for the update, I'd wait for rust-lang/rust#68164 to land then.

**Comment by tmiasko** [comment]
The rust-lang/rust#68164 landed, so this is ready for review & merging.

**Pull request merged**
