### PR TITLE
Document rustc internal env vars a little bit

### PR DESCRIPTION
**Pull request by mark-i-m**
cc #436 @pnkfelix @nikomatsakis @Mark-Simulacrum  https://github.com/rust-lang/rust/issues/38686

From: https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp/topic/env.20vars.20and.20x.2Epy.20.2338686

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Hm, I feel like it's also worth noting that 99% of the time you want to switch from running the bootstrap rustc and instead run `stageN/bin/rustc` or something along those lines, but that can be left for later.

**Comment by mark-i-m** [comment]
@Mark-Simulacrum Could you explain what you mean? Do you mean directly run `./stageN/bin/rustc` rather than `./x.py run ...`?

**Comment by Mark-Simulacrum** [comment]
Yes, I mean to directly run `./stageN/bin/rustc`. I'm not sure what you mean by `./x.py run ...`...

**Comment by mark-i-m** [comment]
Got it. At one point this did not work. It gave errors about environment variables... I haven't tried it recently, though.

> I'm not sure what you mean by ./x.py run ......

I mean running the compiled compiler via `./x.py` (e.g. `./x.py test src/test/ui/blah.rs`)

**Comment by Mark-Simulacrum** [comment]
If `./stageN/bin/rustc` gives an error about environment variables, that usually means something is quite wrong -- or you're trying to compile e.g. librustc or libstd or something that depends on environment variables, but I imagine that's rare (and would be the same anywhere if you skip to a rustc invocation from `cargo build -vv`).

**Comment by mark-i-m** [comment]
@Mark-Simulacrum added a note (mostly verbatim from you post)

**Comment by mark-i-m** [comment]
If it looks good to you, please github-approve and merge.

**Comment by mark-i-m** [comment]
@Mark-Simulacrum ^^^?

**Comment by Mark-Simulacrum** [comment]
Oh that was referring to me! Sorry. Yes, this looks good to me...

**Pull request merged**
