### PR TITLE
Fix mask -> tag terminology

### PR DESCRIPTION
**Pull request by varkor**
Addresses https://github.com/rust-lang/rustc-guide/pull/282#discussion_r265550258.

### CODE REVIEW

**Comment by mark-i-m** [comment]
Hmm... it looks like a bunch of links have broken overnight... I will look into it this weekend.

**Comment by mark-i-m** [comment]
@scalexm Do you know why all of the chalk links broke?

**Comment by Havvy** [comment]
If I had to guess, it's because chalk got moved out of the nursery into @rust-lang/chalk.

It looks like that project should have been under a `Pin<&'links>`.

**Comment by mark-i-m** [comment]
I opened #288 to fix the links, but I'm pretty confident that this fix is ok without travis :P

**Pull request merged**
