### PR TITLE
Add bibligraphy appendix

### PR DESCRIPTION
**Pull request by mark-i-m**
r? @spastorino

### CODE REVIEW

**Comment by Centril** [comment]
Hmm... This should perhaps go into the reference instead but we can have it here as a temporary location.

(More broadly, the rustc guide is starting to become more of the better reference than the actual reference...)

**Comment by mark-i-m** [comment]
> (More broadly, the rustc guide is starting to become more of the better reference than the actual reference...)

In what sense? The rustc-guide is about the compiler, but I can't imagine it would be a very good language spec. Am I misunderstanding you?

**Comment by Centril** [comment]
@mark-i-m In the sense that the rustc-guide has, in places, more formal specification of the language (albeit with many implementation details) than the reference. This is a reflection of the sorry state the reference is in :)

**Comment by spastorino** [comment]
:+1:

**Comment by mark-i-m** [comment]
@Centril I see what you mean, though I would be careful with that line of reasoning, since the guide describes the implementation, so it may over-specify in places (that is, the specification here may be less abstract than what the language actually guarantees).

**Comment by mark-i-m** [comment]
Failure is spurious. Merging.

**Pull request merged**
