### PR TITLE
Breakup the building chapter

### PR DESCRIPTION
**Pull request by mark-i-m**
This PR breaks up the giant "How to Build and Run the Compiler" chapter into a few subchapters:

```diff
-    - [How to Build and Run the Compiler](./how-to-build-and-run.md)
-        - [Build and Install distribution artifacts](./build-install-distribution-artifacts.md)
-        - [Documenting Compiler](./compiler-documenting.md)
+    - [How to Build and Run the Compiler](./building/how-to-build-and-run.md)
+        - [Suggested Workflows](./building/suggested.md)
+        - [Bootstrapping](./building/bootstrapping.md)
+        - [Distribution artifacts](./building/build-install-distribution-artifacts.md)
+        - [Documenting Compiler](./building/compiler-documenting.md)
+        - [ctags](./building/ctags.md)
```

### CODE REVIEW

**Comment by mark-i-m** [comment]
Yes, I added a few filler/intro sentences, but the content is unchanged

**Comment by mark-i-m** [comment]
Do you feel it is an improvement?

**Comment by JohnTitor** [comment]
I agree with this change since I feel "How to Build and Run the Compiler" chapter is long.

**Comment by mark-i-m** [comment]
Cool :) Thanks @JohnTitor @amanjeev  !

**Pull request merged**
